export const PROFESSIONS = [
	{ id: 'SOFTWARE_ENGINEER', value: 'Ingeniero en sistemas' },
	{ id: 'ELECTRIC_ENGINEER', value: 'Ingeniero eléctrico' },
	{ id: 'MECHANICAL_ENGINEER', value: 'Ingeniero mecánico' },
	{ id: 'CIVIL_ENGINEER', value: 'Ingeniero civil' },
	{ id: 'CHEMICAL_ENGINEER', value: 'Ingeniero químico' },
	{ id: 'INDUSTRIAL_ENGINEER', value: 'Ingeniero industrial' },
	{ id: 'AEROSPACE_ENGINEER', value: 'Ingeniero aeroespacial' },
	{ id: 'ENVIRONMENTAL_ENGINEER', value: 'Ingeniero ambiental' },
	{ id: 'BIOMEDICAL_ENGINEER', value: 'Ingeniero biomédico' },
	{ id: 'PETROLEUM_ENGINEER', value: 'Ingeniero petrolero' },
	{ id: 'DOCTOR', value: 'Doctor' },
	{ id: 'NURSE', value: 'Enfermero' },
	{ id: 'TEACHER', value: 'Profesor' },
	{ id: 'LAWYER', value: 'Abogado' },
	{ id: 'ACCOUNTANT', value: 'Contador' },
	{ id: 'ARCHITECT', value: 'Arquitecto' },
	{ id: 'CHEF', value: 'Chef' },
	{ id: 'PHARMACIST', value: 'Farmacéutico' },
	{ id: 'DENTIST', value: 'Dentista' },
	{ id: 'VETERINARIAN', value: 'Veterinario' },
	{ id: 'PSYCHOLOGIST', value: 'Psicólogo' },
	{ id: 'JOURNALIST', value: 'Periodista' },
	{ id: 'PILOT', value: 'Piloto' },
	{ id: 'FIREFIGHTER', value: 'Bombero' },
	{ id: 'POLICE_OFFICER', value: 'Oficial de policía' },
	{ id: 'MUSICIAN', value: 'Músico' },
	{ id: 'ARTIST', value: 'Artista' },
	{ id: 'WRITER', value: 'Escritor' },
	{ id: 'TRANSLATOR', value: 'Traductor' },
	{ id: 'SCIENTIST', value: 'Científico' },
	{ id: 'RESEARCHER', value: 'Investigador' },
	{ id: 'IT_TECHNICIAN', value: 'Técnico de TI' },
	{ id: 'SOCIAL_WORKER', value: 'Trabajador social' },
	{ id: 'ECONOMIST', value: 'Economista' },
	{ id: 'ENTREPRENEUR', value: 'Emprendedor' },
	{ id: 'MARKETER', value: 'Especialista en marketing' },
	{ id: 'DESIGNER', value: 'Diseñador' },
	{ id: 'PHOTOGRAPHER', value: 'Fotógrafo' },
	{ id: 'VIDEOGRAPHER', value: 'Videógrafo' },
	{ id: 'ACTOR', value: 'Actor' },
	{ id: 'DIRECTOR', value: 'Director' },
	{ id: 'PRODUCER', value: 'Productor' }
];
